
export const REQUEST_DISPLAY_PAGE = 'REQUEST_DISPLAY_PAGE';
export const RECEIVE_DISPLAY_PAGE = 'RECEIVE_DISPLAY_PAGE';

export const REQUEST_TWITTER_QUERY = 'REQUEST_TWITTER_QUERY';
export const RECEIVE_TWITTER_QUERY_RESULT = 'RECEIVE_TWITTER_QUERY_RESULT';
export const SET_TWITTER_QUERY = 'SET_TWITTER_QUERY';