// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

using TwitterTools.Web.Models.Json;

namespace TwitterTools.Web.Models.Json
{

    public class User
    {

		[JsonPropertyName("id")]
		public Int64 Id { get; set; }

		[JsonPropertyName("id_str")]
		public string IdStr { get; set; }

		[JsonPropertyName("name")]
		public string Name { get; set; }

		[JsonPropertyName("screen_name")]
		public string ScreenName { get; set; }

		[JsonPropertyName("location")]
		public string Location { get; set; }

		[JsonPropertyName("description")]
		public string Description { get; set; }

		[JsonPropertyName("url")]
		public string Url { get; set; }

		[JsonPropertyName("entities")]
		public UserEntities Entities { get; set; }

		[JsonPropertyName("protected")]
		public bool Protected { get; set; }

		[JsonPropertyName("followers_count")]
		public int FollowersCount { get; set; }

		[JsonPropertyName("friends_count")]
		public int FriendsCount { get; set; }

		[JsonPropertyName("listed_count")]
		public int ListedCount { get; set; }

		[JsonPropertyName("created_at")]
		public string CreatedAt { get; set; }

		[JsonPropertyName("favourites_count")]
		public int FavouritesCount { get; set; }

		[JsonPropertyName("utc_offset")]
		public string UtcOffset { get; set; }

		[JsonPropertyName("time_zone")]
		public string TimeZone { get; set; }

		[JsonPropertyName("geo_enabled")]
		public bool GeoEnabled { get; set; }

		[JsonPropertyName("verified")]
		public bool Verified { get; set; }

		[JsonPropertyName("statuses_count")]
		public int StatusesCount { get; set; }

		[JsonPropertyName("lang")]
		public string Lang { get; set; }

		[JsonPropertyName("contributors_enabled")]
		public bool ContributorsEnabled { get; set; }

		[JsonPropertyName("is_translator")]
		public bool IsTranslator { get; set; }

		[JsonPropertyName("profile_background_color")]
		public string ProfileBackgroundColor { get; set; }

		[JsonPropertyName("profile_background_image_url")]
		public string ProfileBackgroundImageUrl { get; set; }

		[JsonPropertyName("profile_background_image_url_https")]
		public string ProfileBackgroundImageUrlHttps { get; set; }

		[JsonPropertyName("profile_background_tile")]
		public bool ProfileBackgroundTile { get; set; }

		[JsonPropertyName("profile_image_url")]
		public string ProfileImageUrl { get; set; }

		[JsonPropertyName("profile_image_url_https")]
		public string ProfileImageUrlHttps { get; set; }

		[JsonPropertyName("profile_link_color")]
		public string ProfileLinkColor { get; set; }

		[JsonPropertyName("profile_sidebar_border_color")]
		public string ProfileSidebarBorderColor { get; set; }

		[JsonPropertyName("profile_sidebar_fill_color")]
		public string ProfileSidebarFillColor { get; set; }

		[JsonPropertyName("profile_text_color")]
		public string ProfileTextColor { get; set; }

		[JsonPropertyName("profile_use_background_image")]
		public bool ProfileUseBackgroundImage { get; set; }

		[JsonPropertyName("default_profile")]
		public bool DefaultProfile { get; set; }

		[JsonPropertyName("default_profile_image")]
		public bool DefaultProfileImage { get; set; }

		[JsonPropertyName("following")]
		public string Following { get; set; }

		[JsonPropertyName("follow_request_sent")]
		public string FollowRequestSent { get; set; }

		[JsonPropertyName("notifications")]
		public string Notifications { get; set; }
    }

}
